/* Table: COMPS */

CREATE TABLE COMPS (
    ID INTEGER NOT NULL,
    NUMBER VARCHAR(10) NOT NULL,
    NETWORK_NAME VARCHAR(30) NOT NULL,
    IP_ADDRESS VARCHAR(100) NOT NULL,
    CLASS INTEGER NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    VALID INTEGER NOT NULL,
    COMMENTS VARCHAR(500),
    CHANGE_TIME TIMESTAMP DEFAULT 'now' NOT NULL,
    HASHSUM INTEGER NOT NULL);





/* Primary keys definition */

ALTER TABLE COMPS ADD PRIMARY KEY (ID);


/* Indices definition */

CREATE UNIQUE INDEX COMPS_IDX1 ON COMPS (NUMBER, VALID);
CREATE INDEX COMPS_IDX2 ON COMPS (CLASS);
CREATE INDEX COMPS_IDX3 ON COMPS (NUMBER);
CREATE INDEX COMPS_IDX4 ON COMPS (DESCRIPTION);
CREATE INDEX COMPS_IDX5 ON COMPS (NETWORK_NAME, VALID);
CREATE UNIQUE INDEX COMPS_IDX6 ON COMPS (IP_ADDRESS, VALID);
/* Triggers definition */


SET TERM ^ ;





/* Trigger: COMPS_AU0 */
CREATE TRIGGER COMPS_AU0 FOR COMPS
ACTIVE AFTER UPDATE POSITION 0
as
begin
  insert into CMP_VALID_CHANGES
   (CHANGE_TIME, OLD_VALUE, NEW_VALUE, CMP_ID)
  values
   ('now', old.VALID, new.VALID, new.ID);
end
^

/* Trigger: COMPS_BI0 */
CREATE TRIGGER COMPS_BI0 FOR COMPS
ACTIVE BEFORE INSERT POSITION 0
as
begin
 new.HASHSUM=0;
end
^

/* Trigger: COMPS_BU0 */
CREATE TRIGGER COMPS_BU0 FOR COMPS
ACTIVE BEFORE UPDATE POSITION 0
as
begin
 NEW.CHANGE_TIME = 'now';
end
^


SET TERM ; ^
