/* Table: TRF_PRICE_CHANGES */

CREATE TABLE TRF_PRICE_CHANGES (
    CHANGE_TIME TIMESTAMP NOT NULL,
    OLD_VALUE DOUBLE PRECISION NOT NULL,
    NEW_VALUE DOUBLE PRECISION NOT NULL,
    TRF_ID INTEGER NOT NULL);



