/* Table: UNORDER_TIME */

CREATE TABLE UNORDER_TIME (
    REC_ID INTEGER NOT NULL,
    COMP_ID INTEGER NOT NULL,
    COMP_NAME VARCHAR(10) NOT NULL,
    NETWORK_NAME VARCHAR(30) NOT NULL,
    TIME_START TIMESTAMP NOT NULL,
    TIME_STOP TIMESTAMP NOT NULL);



